name: flutter_wechat
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_webview_plugin: ^0.3.11
  date_format: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/loading.png

   # 底部 tabbar 图标
   - assets/images/tabbar/contact_normal.png
   - assets/images/tabbar/contact_pressed.png
   - assets/images/tabbar/find_normal.png
   - assets/images/tabbar/find_pressed.png
   - assets/images/tabbar/profile_normal.png
   - assets/images/tabbar/profile_pressed.png
   - assets/images/tabbar/weixin_normal.png
   - assets/images/tabbar/weixin_pressed.png

   # 头像
   - assets/images/avatar.png

   # 图标
   - assets/images/icon/add_friends.png
   - assets/images/icon/email.png
   - assets/images/icon/scan.png
   - assets/images/icon/scanframe.png
   - assets/images/icon/send.png

   # 通讯录
   - assets/images/icon/groupchat.png
   - assets/images/icon/tag.png
   - assets/images/icon/public.png

   # 发现页
   - assets/images/icon/friends.png
   - assets/images/icon/right.png
   - assets/images/icon/game.png
   - assets/images/icon/shake.png
   - assets/images/icon/applet.png
   - assets/images/icon/bottle.png
   - assets/images/icon/shop.png
   - assets/images/icon/people.png

   # 我的
   - assets/images/icon/code.png
   - assets/images/icon/pay.png
   - assets/images/icon/collection.png
   - assets/images/icon/album.png
   - assets/images/icon/cardbag.png
   - assets/images/icon/expression.png
   - assets/images/icon/setting.png
   - assets/images/icon/camera.png

   # 静态资源
   - assets/static/qrcode.jpg

   # 支付界面
   - assets/images/payment/payscan.png
   - assets/images/payment/wallet.png

   - assets/images/payment/credit_card.png
   - assets/images/payment/loan.png
   - assets/images/payment/phone_recharge.png
   - assets/images/payment/conduct.png
   - assets/images/payment/living_expenses.png
   - assets/images/payment/qcoin.png
   - assets/images/payment/urban_services.png
   - assets/images/payment/welfare.png
   - assets/images/payment/medical_care.png

   - assets/images/payment/health_code.png
   - assets/images/payment/starbucks.png

   - assets/images/payment/train_ticket.png
   - assets/images/payment/didi.png
   - assets/images/payment/jd.png
   - assets/images/payment/meituan.png
   - assets/images/payment/maoyan.png
   - assets/images/payment/pingduoduo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
